export const metadata = {
  title: "Profile",
  description: "Generated by create next app",
};
export default async function ProfilePageLayout({searchParams,params,children}){
    const { clientType } = await params;
    const clientRole = clientType[0];
    return(
        <>
        {children} 
        </>
    )
}